package com.ihvncr.ihvncrapi.mongo.model;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//



import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.*;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;


/**
 * <p>Java class for MessageHeaderType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MessageHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageStatusCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="EXPORTED"/>
 *               &lt;enumeration value="UPLOADED"/>
 *               &lt;enumeration value="VALIDATING"/>
 *               &lt;enumeration value="VALIDATED"/>
 *               &lt;enumeration value="LOADING"/>
 *               &lt;enumeration value="LOADED"/>
 *               &lt;enumeration value="PENDING"/>
 *               &lt;enumeration value="REJECTED"/>
 *               &lt;enumeration value="ERROR"/>
 *               &lt;enumeration value="PAUSED"/>
 *               &lt;enumeration value="PROCESSING"/>
 *               &lt;enumeration value="PROCESSED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MessageSource">
 *           &lt;simpleType>
 *             &lt;restriction base="{}CodeType">
 *               &lt;enumeration value="NMRS"/>
 *               &lt;enumeration value="NOMIS"/>
 *               &lt;enumeration value="LIMS"/>
 *               &lt;enumeration value="HTSAPP"/>
 *               &lt;enumeration value="DHIS2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MessageCreationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="MessageSchemaVersion">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="99999"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MessageUniqueID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FacilityDatimCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FacilityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UploadDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ProcessedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="invalid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="validation_error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="touch_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageHeaderType", propOrder = {
        "messageStatusCode",
        "messageSource",
        "messageCreationDateTime",
        "messageSchemaVersion",
        "messageUniqueID",
        "facilityDatimCode",
        "facilityName",
        "facilityLga",
        "facilityState",
        "fileName",
        "uploadDate",
        "processedDate",
        "invalid",
        "validationError",
        "touchTime"
})
@Getter
@Setter
public class MessageHeaderType implements Serializable {

    @XmlElement(name = "MessageStatusCode", required = true)
    protected String messageStatusCode;
    @XmlElement(name = "MessageSource", required = true)
    protected String messageSource;
    @XmlElement(name = "MessageCreationDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date messageCreationDateTime;
    @XmlElement(name = "MessageSchemaVersion", required = true)
    protected BigDecimal messageSchemaVersion;
    @XmlElement(name = "MessageUniqueID", required = true)
    protected String messageUniqueID;
    @XmlElement(name = "FacilityDatimCode", required = true)
    protected String facilityDatimCode;
    @XmlElement(name = "FacilityName", required = true)
    protected String facilityName;
    private String facilityLga;

    private String facilityState;
    @XmlElement(name = "FileName", required = true)
    protected String fileName;
    @XmlElement(name = "UploadDate")
    @XmlSchemaType(name = "dateTime")
    protected Date uploadDate;
    @XmlElement(name = "ProcessedDate")
    @XmlSchemaType(name = "dateTime")
    protected Date processedDate;
    protected int invalid;
    @XmlElement(name = "validation_error", required = true)
    protected String validationError;
    @XmlElement(name = "touch_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date touchTime;

}
