package com.ihvncr.ihvncrapi.mongo.model;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.*;
import java.io.Serializable;
import java.util.Date;
import java.util.Objects;


/**
 * <p>Java class for VisitType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VisitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{<a href="http://www.w3.org/2001/XMLSchema">...</a>}anyType">
 *       &lt;sequence>
 *         &lt;element name="visit_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="patient_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="location_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="visit_type_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="date_started" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="date_stopped" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="creator" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="date_created" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="changed_by" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="date_changed" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="voided" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="voided_by" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="date_voided" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="patient_uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datim_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="visit_uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisitType", propOrder = {
        "visitId",
        "patientId",
        "locationId",
        "visitTypeId",
        "dateStarted",
        "dateStopped",
        "creator",
        "dateCreated",
        "changedBy",
        "dateChanged",
        "voided",
        "voidedBy",
        "dateVoided",
        "patientUuid",
        "datimId",
        "visitUuid"
})
@Getter
@Setter
public class VisitType implements Serializable {

    @XmlElement(name = "visit_id")
    protected int visitId;
    @XmlElement(name = "patient_id")
    protected int patientId;
    @XmlElement(name = "location_id")
    protected int locationId;
    @XmlElement(name = "visit_type_id")
    protected int visitTypeId;
    @XmlElement(name = "date_started", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date dateStarted;
    @XmlElement(name = "date_stopped", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date dateStopped;
    protected int creator;
    @XmlElement(name = "date_created", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date dateCreated;
    @XmlElement(name = "changed_by")
    protected int changedBy;
    @XmlElement(name = "date_changed", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date dateChanged;
    protected int voided;
    @XmlElement(name = "voided_by")
    protected int voidedBy;
    @XmlElement(name = "date_voided", required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date dateVoided;
    @XmlElement(name = "patient_uuid", required = true)
    protected String patientUuid;
    @XmlElement(name = "datim_id", required = true)
    protected String datimId;
    @XmlElement(name = "visit_uuid", required = true)
    protected String visitUuid;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof VisitType)) return false;
        VisitType visitType = (VisitType) o;
        return getVisitId() == visitType.getVisitId() && getPatientId() == visitType.getPatientId() && Objects.equals(getPatientUuid(), visitType.getPatientUuid()) && Objects.equals(getVisitUuid(), visitType.getVisitUuid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getVisitId(), getPatientId(), getPatientUuid(), getVisitUuid());
    }
}
