package com.ihvncr.ihvncrapi.service;

import com.ihvncr.ihvncrapi.model.ArtLinelist;
import org.apache.poi.ss.usermodel.*;
import org.springframework.web.servlet.view.document.AbstractXlsxView;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.List;
import java.util.Map;
public class ArtLineListDataExport extends AbstractXlsxView {

    @Override
    protected void buildExcelDocument(
            Map<String, Object> map, Workbook workbook, HttpServletRequest httpServletRequest,
            HttpServletResponse httpServletResponse) {
        @SuppressWarnings("unchecked")
        List<ArtLinelist> linelists = (List<ArtLinelist>) map.get("list");

        String facilityName = !linelists.isEmpty() ? linelists.get(0).getFacilityName() : "";
        httpServletResponse.addHeader("Content-Disposition", "attachment;fileName="+facilityName+"_ArtLineList.xlsx");

        CellStyle cellStyle = workbook.createCellStyle();
        CreationHelper createHelper = workbook.getCreationHelper();
        cellStyle.setDataFormat(createHelper.createDataFormat().getFormat("d-mmm-yy"));
        Sheet sheet = workbook.createSheet();
        Row row0 = sheet.createRow(0);
        row0.createCell(0).setCellValue("State");
        row0.createCell(1).setCellValue("LGA");
        row0.createCell(2).setCellValue("DatimCode");
        row0.createCell(3).setCellValue("FacilityName");
        row0.createCell(4).setCellValue("PatientUniqueID");
        row0.createCell(5).setCellValue("PatientHospitalNo");
        row0.createCell(6).setCellValue("ANCNoIdentifier");
        row0.createCell(7).setCellValue("ANCNoConceptID");
        row0.createCell(8).setCellValue("HTSNo");
        row0.createCell(9).setCellValue("Sex");
        row0.createCell(10).setCellValue("AgeAtStartOfARTYears");
        row0.createCell(11).setCellValue("AgeAtStartOfARTMonths");
        row0.createCell(12).setCellValue("CareEntryPoint");
        row0.createCell(13).setCellValue("KPType");
        row0.createCell(14).setCellValue("MonthsOnART");
        row0.createCell(15).setCellValue("DateTransferredIn");
        row0.createCell(16).setCellValue("TransferInStatus");
        row0.createCell(17).setCellValue("ARTStartDate");
        row0.createCell(18).setCellValue("LastPickupDate");
        row0.createCell(19).setCellValue("LastVisitDate");
        row0.createCell(20).setCellValue("DaysOfARVRefil");
        row0.createCell(21).setCellValue("PillBalance");
        row0.createCell(22).setCellValue("InitialRegimenLine");
        row0.createCell(23).setCellValue("InitialRegimen");
        row0.createCell(24).setCellValue("InitialCD4Count");
        row0.createCell(25).setCellValue("InitialCD4CountDate");
        row0.createCell(26).setCellValue("CurrentCD4Count");
        row0.createCell(27).setCellValue("CurrentCD4CountDate");
        row0.createCell(28).setCellValue("LastEACDate");
        row0.createCell(29).setCellValue("CurrentRegimenLine");
        row0.createCell(30).setCellValue("CurrentRegimen");
        row0.createCell(31).setCellValue("PregnancyStatus");
        row0.createCell(32).setCellValue("PregnancyStatusDate");
        row0.createCell(33).setCellValue("EDD");
        row0.createCell(34).setCellValue("LastDeliveryDate");
        row0.createCell(35).setCellValue("LMP");
        row0.createCell(36).setCellValue("GestationAgeWeeks");
        row0.createCell(37).setCellValue("CurrentViralLoad(c/ml)");
        row0.createCell(38).setCellValue("ViralLoadEncounterDate");
        row0.createCell(39).setCellValue("ViralLoadSampleCollectionDate");
        row0.createCell(40).setCellValue("ViralLoadReportedDate");
        row0.createCell(41).setCellValue("ResultDate");
        row0.createCell(42).setCellValue("AssayDate");
        row0.createCell(43).setCellValue("ApprovalDate");
        row0.createCell(44).setCellValue("ViralLoadIndication");
        row0.createCell(45).setCellValue("PatientOutcome");
        row0.createCell(46).setCellValue("PatientOutcomeDate");
        row0.createCell(47).setCellValue("CurrentARTStatus");
        row0.createCell(48).setCellValue("DispensingModality");
        row0.createCell(49).setCellValue("FacilityDispensingModality");
        row0.createCell(50).setCellValue("DDDDispensingModality");
        row0.createCell(51).setCellValue("MMDType");
        row0.createCell(52).setCellValue("DateReturnedToCare");
        row0.createCell(53).setCellValue("DateOfTermination");
        row0.createCell(54).setCellValue("PharmacyNextAppointment");
        row0.createCell(55).setCellValue("ClinicalNextAppointment");
        row0.createCell(56).setCellValue("CurrentAgeYears");
        row0.createCell(57).setCellValue("CurrentAgeMonths");
        row0.createCell(58).setCellValue("DateOfBirth");
        row0.createCell(59).setCellValue("MarkAsDeseased");
        row0.createCell(60).setCellValue("MarkAsDeseasedDeathDate");
        row0.createCell(61).setCellValue("RegistrationPhoneNo");
        row0.createCell(62).setCellValue("NextofKinPhoneNo");
        row0.createCell(63).setCellValue("TreatmentSupporterPhoneNo");
        row0.createCell(64).setCellValue("BiometricCaptured");
        row0.createCell(65).setCellValue("BiometricCaptureDate");
        row0.createCell(66).setCellValue("ValidCapture");
        row0.createCell(67).setCellValue("CurrentWeight(Kg)");
        row0.createCell(68).setCellValue("CurrentWeightDate");
        row0.createCell(69).setCellValue("TBStatus");
        row0.createCell(70).setCellValue("TBStatusDate");
        row0.createCell(71).setCellValue("BaselineINHStartDate");
        row0.createCell(72).setCellValue("BaselineINHStopDate");
        row0.createCell(73).setCellValue("CurrentINHStartDate");
        row0.createCell(74).setCellValue("CurrentINHOutcome");
        row0.createCell(75).setCellValue("CurrentINHOutcomeDate");
        row0.createCell(76).setCellValue("LastINHDispensedDate");
        row0.createCell(77).setCellValue("BaselineTBTreatmentStartDate");
        row0.createCell(78).setCellValue("BaselineTBTreatmentStopDate");
        row0.createCell(79).setCellValue("LastViralLoadSampleCollectionFormDate");
        row0.createCell(80).setCellValue("LastSampleTakenDate");
        row0.createCell(81).setCellValue("OTZEnrollmentDate");
        row0.createCell(82).setCellValue("OTZOutcomeDate");
        row0.createCell(83).setCellValue("EnrollmentDate");
        row0.createCell(84).setCellValue("InitialFirstLineRegimen");
        row0.createCell(85).setCellValue("InitialFirstLineRegimenDate");
        row0.createCell(86).setCellValue("InitialSecondLineRegimen");
        row0.createCell(87).setCellValue("InitialSecondLineRegimenDate");
        row0.createCell(88).setCellValue("LastPickupDatePreviousQuarter");
        row0.createCell(89).setCellValue("DrugDurationPreviousQuarter");
        row0.createCell(90).setCellValue("PatientOutcomePreviousQuarter");
        row0.createCell(91).setCellValue("PatientOutcomeDatePreviousQuarter");
        row0.createCell(92).setCellValue("ARTStatusPreviousQuarter");

        int rowNum = 1;
        for (ArtLinelist artLinelist : linelists) {
            Row row = sheet.createRow(rowNum++);
            row.createCell(0).setCellValue(artLinelist.getState());
            row.createCell(1).setCellValue(artLinelist.getLgaName());
            row.createCell(2).setCellValue(artLinelist.getDatimCode());
            row.createCell(3).setCellValue(artLinelist.getFacilityName());
            row.createCell(4).setCellValue(artLinelist.getPatientUniqueId());
            row.createCell(5).setCellValue(artLinelist.getPatientHospitalNo());
            row.createCell(6).setCellValue(artLinelist.getAncNoIdentifier());
            row.createCell(7).setCellValue(artLinelist.getAncNoConceptId());
            row.createCell(8).setCellValue(artLinelist.getHtsNo());
            row.createCell(9).setCellValue(artLinelist.getSex());
            row.createCell(10).setCellValue(artLinelist.getAgeAtStartOfArtYears() != null ? artLinelist.getAgeAtStartOfArtYears() : 0);
            row.createCell(11).setCellValue(artLinelist.getAgeAtStartOfArtMonths() != null ? artLinelist.getAgeAtStartOfArtMonths() : 0);
            row.createCell(12).setCellValue(artLinelist.getCareEntryPoint());
            row.createCell(13).setCellValue(artLinelist.getKpType());
            row.createCell(14).setCellValue(artLinelist.getMonthsOnArt() != null ? artLinelist.getMonthsOnArt() : 0);
            Cell dateTransferredIn = row.createCell(15);
            dateTransferredIn.setCellValue(artLinelist.getDateTransferredIn());
            dateTransferredIn.setCellStyle(cellStyle);
            row.createCell(16).setCellValue(artLinelist.getTransferInStatus());
            Cell artStartDate = row.createCell(17);
            artStartDate.setCellValue(artLinelist.getArtStartDate());
            artStartDate.setCellStyle(cellStyle);
            Cell lastPickupDate = row.createCell(18);
            lastPickupDate.setCellValue(artLinelist.getLastPickupDate());
            lastPickupDate.setCellStyle(cellStyle);
            Cell lastVisitDate = row.createCell(19);
            lastVisitDate.setCellValue(artLinelist.getLastVisitDate());
            lastVisitDate.setCellStyle(cellStyle);
            row.createCell(20).setCellValue(artLinelist.getDaysOfArvRefil() != null ? artLinelist.getDaysOfArvRefil() : 0);
            row.createCell(21).setCellValue(artLinelist.getPillBalance() != null ? artLinelist.getPillBalance() : 0);
            row.createCell(22).setCellValue(artLinelist.getInitialRegimenLine());
            row.createCell(23).setCellValue(artLinelist.getInitialRegimen());
            row.createCell(24).setCellValue(artLinelist.getInitialCd4Count() != null ? artLinelist.getInitialCd4Count() : 0);
            Cell initialCd4CountDate = row.createCell(25);
            initialCd4CountDate.setCellValue(artLinelist.getInitialCd4CountDate());
            initialCd4CountDate.setCellStyle(cellStyle);
            row.createCell(26).setCellValue(artLinelist.getCurrentCd4Count() != null ? artLinelist.getCurrentCd4Count() : 0);
            Cell currentCd4CountDate = row.createCell(27);
            currentCd4CountDate.setCellValue(artLinelist.getCurrentCd4CountDate());
            currentCd4CountDate.setCellStyle(cellStyle);
            Cell lastEacDate = row.createCell(28);
            lastEacDate.setCellValue(artLinelist.getLastEacDate());
            lastEacDate.setCellStyle(cellStyle);
            row.createCell(29).setCellValue(artLinelist.getCurrentRegimenLine());
            row.createCell(30).setCellValue(artLinelist.getCurrentRegimen());
            row.createCell(31).setCellValue(artLinelist.getPregnancyStatus());
            Cell pregnancyStatusDate = row.createCell(32);
            pregnancyStatusDate.setCellValue(artLinelist.getPregnancyStatusDate());
            pregnancyStatusDate.setCellStyle(cellStyle);
            Cell edd = row.createCell(33);
            edd.setCellValue(artLinelist.getEdd());
            edd.setCellStyle(cellStyle);
            Cell lastDeliveryDate = row.createCell(34);
            lastDeliveryDate.setCellValue(artLinelist.getLastDeliveryDate());
            lastDeliveryDate.setCellStyle(cellStyle);
            Cell lmp = row.createCell(35);
            lmp.setCellValue(artLinelist.getLmp());
            lmp.setCellStyle(cellStyle);
            row.createCell(36).setCellValue(artLinelist.getGestationAgeWeeks() != null ? artLinelist.getGestationAgeWeeks() : 0);
            row.createCell(37).setCellValue(artLinelist.getCurrentViralLoad() != null ? artLinelist.getCurrentViralLoad() : 0);
            Cell viralLoadEncounterDate = row.createCell(38);
            viralLoadEncounterDate.setCellValue(artLinelist.getViralLoadEncounterDate());
            viralLoadEncounterDate.setCellStyle(cellStyle);
            Cell viralLoadSampleCollectionDate = row.createCell(39);
            viralLoadSampleCollectionDate.setCellValue(artLinelist.getViralLoadSampleCollectionDate());
            viralLoadSampleCollectionDate.setCellStyle(cellStyle);
            Cell viralLoadReportedDate = row.createCell(40);
            viralLoadReportedDate.setCellValue(artLinelist.getViralLoadReportedDate());
            viralLoadReportedDate.setCellStyle(cellStyle);
            Cell resultDate = row.createCell(41);
            resultDate.setCellValue(artLinelist.getResultDate());
            resultDate.setCellStyle(cellStyle);
            Cell assayDate = row.createCell(42);
            assayDate.setCellValue(artLinelist.getAssayDate());
            assayDate.setCellStyle(cellStyle);
            Cell approvalDate = row.createCell(43);
            approvalDate.setCellValue(artLinelist.getApprovalDate());
            approvalDate.setCellStyle(cellStyle);
            row.createCell(44).setCellValue(artLinelist.getViralLoadIndication());
            row.createCell(45).setCellValue(artLinelist.getPatientOutcome());
            Cell patientOutcomeDate = row.createCell(46);
            patientOutcomeDate.setCellValue(artLinelist.getPatientOutcomeDate());
            patientOutcomeDate.setCellStyle(cellStyle);
            row.createCell(47).setCellValue(artLinelist.getCurrentArtStatus());
            row.createCell(48).setCellValue(artLinelist.getDispensingModality());
            row.createCell(49).setCellValue(artLinelist.getFacilityDispensingModality());
            row.createCell(50).setCellValue(artLinelist.getDddDispensingModality());
            row.createCell(51).setCellValue(artLinelist.getMmdType());
            Cell DateReturnedToCare = row.createCell(52);
            DateReturnedToCare.setCellValue(artLinelist.getDateReturnedToCare());
            DateReturnedToCare.setCellStyle(cellStyle);
            Cell dateOfTermination = row.createCell(53);
            dateOfTermination.setCellValue(artLinelist.getDateOfTermination());
            dateOfTermination.setCellStyle(cellStyle);
            Cell pharmacyNextAppointment = row.createCell(54);
            pharmacyNextAppointment.setCellValue(artLinelist.getPharmacyNextAppointment());
            pharmacyNextAppointment.setCellStyle(cellStyle);
            Cell clinicalNextAppointment = row.createCell(55);
            clinicalNextAppointment.setCellValue(artLinelist.getClinicalNextAppointment());
            clinicalNextAppointment.setCellStyle(cellStyle);
            row.createCell(56).setCellValue(artLinelist.getCurrentAgeYrs() != null ? artLinelist.getCurrentAgeYrs() : 0);
            row.createCell(57).setCellValue(artLinelist.getCurrentAgeMonths() != null ? artLinelist.getCurrentAgeMonths() : 0);
            Cell dateOfBirth = row.createCell(58);
            dateOfBirth.setCellValue(artLinelist.getDateOfBirth());
            dateOfBirth.setCellStyle(cellStyle);
            row.createCell(59).setCellValue(artLinelist.getMarkAsDeceased());
            Cell markAsDeceasedDate = row.createCell(60);
            markAsDeceasedDate.setCellValue(artLinelist.getMarkAsDeceasedDeathDate());
            markAsDeceasedDate.setCellStyle(cellStyle);
            row.createCell(61).setCellValue(artLinelist.getRegistrationPhoneNo());
            row.createCell(62).setCellValue(artLinelist.getNextOfKinPhoneNo());
            row.createCell(63).setCellValue(artLinelist.getTreatmentSupporterPhoneNo());
            row.createCell(64).setCellValue(artLinelist.getBiometricCaptured());
            Cell biometricCapturedDate = row.createCell(65);
            biometricCapturedDate.setCellValue(artLinelist.getBiometricCaptureDate());
            biometricCapturedDate.setCellStyle(cellStyle);
            row.createCell(66).setCellValue(artLinelist.getValidCapture());
            row.createCell(67).setCellValue(artLinelist.getCurrentWeight() != null ? artLinelist.getCurrentWeight() : 0);
            Cell currentWeightDate = row.createCell(68);
            currentWeightDate.setCellValue(artLinelist.getCurrentWeightDate());
            currentWeightDate.setCellStyle(cellStyle);
            row.createCell(69).setCellValue(artLinelist.getTbStatus());
            Cell tbStatusDate = row.createCell(70);
            tbStatusDate.setCellValue(artLinelist.getTbStatusDate());
            tbStatusDate.setCellStyle(cellStyle);
            Cell baselineInhStartDate = row.createCell(71);
            baselineInhStartDate.setCellValue(artLinelist.getBaselineInhStartDate());
            baselineInhStartDate.setCellStyle(cellStyle);
            Cell baselineInhStopDate = row.createCell(72);
            baselineInhStopDate.setCellValue(artLinelist.getBaselineInhStopDate());
            baselineInhStopDate.setCellStyle(cellStyle);
            Cell currentInhStartDate = row.createCell(73);
            currentInhStartDate.setCellValue(artLinelist.getCurrentInhStartDate());
            currentInhStartDate.setCellStyle(cellStyle);
            row.createCell(74).setCellValue(artLinelist.getCurrentInhOutcome());
            Cell currentInhOutcomeDate = row.createCell(75);
            currentInhOutcomeDate.setCellValue(artLinelist.getCurrentInhOutcomeDate());
            currentInhOutcomeDate.setCellStyle(cellStyle);
            Cell lastInhDispensedDate = row.createCell(76);
            lastInhDispensedDate.setCellValue(artLinelist.getLastInhDispensedDate());
            lastInhDispensedDate.setCellStyle(cellStyle);
            Cell baselineTbTreatmentStartDate = row.createCell(77);
            baselineTbTreatmentStartDate.setCellValue(artLinelist.getBaselineTbTreatmentStartDate());
            baselineTbTreatmentStartDate.setCellStyle(cellStyle);
            Cell baselineTbTreatmentStopDate = row.createCell(78);
            baselineTbTreatmentStopDate.setCellValue(artLinelist.getBaselineTbTreatmentStopDate());
            baselineTbTreatmentStopDate.setCellStyle(cellStyle);
            Cell lastViralLoadSampleCollectionFormDate = row.createCell(79);
            lastViralLoadSampleCollectionFormDate.setCellValue(artLinelist.getLastViralLoadSampleCollectionFormDate());
            lastViralLoadSampleCollectionFormDate.setCellStyle(cellStyle);
            Cell lastSampleTakenDate = row.createCell(80);
            lastSampleTakenDate.setCellValue(artLinelist.getLastSampleTakenDate());
            lastSampleTakenDate.setCellStyle(cellStyle);
            Cell otzEnrollmentDate = row.createCell(81);
            otzEnrollmentDate.setCellValue(artLinelist.getOtzEnrollmentDate());
            otzEnrollmentDate.setCellStyle(cellStyle);
            Cell otzOutcomeDate = row.createCell(82);
            otzOutcomeDate.setCellValue(artLinelist.getOtzOutcomeDate());
            otzOutcomeDate.setCellStyle(cellStyle);
            Cell enrollmentDate = row.createCell(83);
            enrollmentDate.setCellValue(artLinelist.getEnrollmentDate());
            enrollmentDate.setCellStyle(cellStyle);
            row.createCell(84).setCellValue(artLinelist.getInitialFirstLineRegimen());
            Cell initialFirstLineRegimenDate = row.createCell(85);
            initialFirstLineRegimenDate.setCellValue(artLinelist.getInitialFirstLineRegimenDate());
            initialFirstLineRegimenDate.setCellStyle(cellStyle);
            row.createCell(86).setCellValue(artLinelist.getInitialSecondLineRegimen());
            Cell initialSecondLineRegimenDate = row.createCell(87);
            initialSecondLineRegimenDate.setCellValue(artLinelist.getInitialSecondLineRegimenDate());
            initialSecondLineRegimenDate.setCellStyle(cellStyle);
            Cell lastPickupDatePreviousQuarter = row.createCell(88);
            lastPickupDatePreviousQuarter.setCellValue(artLinelist.getLastPickupDatePreviousQuarter());
            lastPickupDatePreviousQuarter.setCellStyle(cellStyle);
            row.createCell(89).setCellValue(artLinelist.getDrugDurationPreviousQuarter() != null ? artLinelist.getDrugDurationPreviousQuarter().intValue() : 0);
            row.createCell(90).setCellValue(artLinelist.getPatientOutcomePreviousQuarter());
            Cell patientOutcomeDatePreviousQuarter = row.createCell(91);
            patientOutcomeDatePreviousQuarter.setCellValue(artLinelist.getPatientOutcomeDatePreviousQuarter());
            patientOutcomeDatePreviousQuarter.setCellStyle(cellStyle);
            row.createCell(92).setCellValue(artLinelist.getArtStatusPreviousQuarter());
        }
    }
}
